package contact.enums;

public enum ManagerState {
  INIT,
  GET_COMMAND,
  GET_ALL_CONTACTS,
  CREATE_NEW_CONTACT,
  DELETE_CONTACT,
  EDIT_CONTACT,
  PRINT_CONTACT_DETAILS,
  GET_CONTACT_IN_ORDER,
  GET_CONTACT_BY_SEARCH_PARAM,
  END
}