package contact.enums;

public enum ManagerState {
  GET_COMMAND, END, INIT, CREATE_NEW_CONTACT, DELETE_CONTACT, EDIT_CONTACT,
  PRINT_CONTACT_DETAILS, SAVE_REPOSITORY, LOAD_REPOSITORY, NOT_IMPLEMENTET, GET_CONTACT_IN_ORDER,
  GET_CONTACT_BY_SEARCH_PARAM, GET_ALL_CONTACTS
}